version: "3.5"
services:
    postgres:
        image: postgres:12.3-alpine
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"

    web:
        build: .
        command: bash -c "
            python manage.py migrate
            && python manage.py loaddata fixtures/admin.json
            && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - postgres